- pipeline.id: test_file_input
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "./config/pipelines/file_input.conf"
- pipeline.id: test_http_input
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "./config/pipelines/http_input.conf"
- pipeline.id: test_jdbc_input
  pipeline.workers: 1
  pipeline.batch.size: 1
  path.config: "./config/pipelines/jdbc_input.conf"